ci: update docs build with retry

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -24,7 +24,18 @@ jobs:
       uses: actions/configure-pages@v5
         
     - name: Generate Docs
-      run: xcodebuild docbuild -scheme jose-swift-docs -destination "platform=macOS" -derivedDataPath ./doccBuild OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ./docc --hosting-base-path '/jose-swift'"
+      run: |
+        max_attempts=5
+        count=0
+        until xcodebuild docbuild -scheme jose-swift-docs -destination "platform=macOS" -derivedDataPath ./doccBuild OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ./docc --hosting-base-path '/jose-swift'" ; do
+        ((count++))
+        if [ $count -eq $max_attempts ]; then
+            echo "Documentation build failed after $max_attempts attempts."
+            exit 1
+        fi
+        echo "Documentation build failed. Retrying attempt $((count+1))/$max_attempts..."
+        sleep 5
+        done
 
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
